name: Build APK

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Extract project
        run: |
          unzip -q yntymak_muras_flutter_v0_1.zip -d project
          echo "Folders:"
          find project -maxdepth 3 -type f -name pubspec.yaml

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.0'
          channel: stable

      - name: Find project and build
        run: |
          PROJECT=$(find project -name pubspec.yaml -printf '%h\n' | head -1)
          echo "Flutter project: $PROJECT"
          cd "$PROJECT"
          flutter pub get
          flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: yntymak-muras-apk
          path: project/**/build/app/outputs/flutter-apk/app-release.apk
